//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cron_reminder")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub chat_id: i64,
    pub cron_expr: String,
    pub time: NaiveDateTime,
    pub desc: String,
    pub user_id: Option<i64>,
    pub paused: bool,
    pub msg_id: Option<i32>,
    pub reply_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
