//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2
#![allow(unused_imports)]

pub use super::reminder::Entity as Reminder;
pub use super::user_language::Entity as UserLanguage;
pub use super::user_timezone::Entity as UserTimezone;
