//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.2

use crate::entity::common::EditMode;
use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reminder")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub chat_id: i64,
    pub time: NaiveDateTime,
    pub desc: String,
    pub edit: bool,
    pub edit_mode: EditMode,
    pub user_id: Option<i64>,
    pub paused: bool,
    pub pattern: Option<String>,
    pub msg_id: Option<i32>,
    pub reply_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
